version: '3'
services:
  app:
    build: .
    restart: on-failure
    ports:
      - 9229:9229
      - 8080:8080
    volumes: 
      - .:/app
    env_file: server/.env.local
  mongo:
    image: mongo:4.4.3-bionic
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password 
  redis:
    image: redis:6.0.10-alpine
    restart: on-failure
